favicon: null
name: Lifeismyfavouritecolor
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.6553192
  brandColors:
    - '#F9E9C6'
    - '#D0C5B2'
    - '#306491'
    - '#9AA3A3'
  rhythmicContrast: 0.01276596
typography_spectrum: 0.26775
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
